// src/lib/targetCompanies.ts
export const TARGET_COMPANIES = [
  // Consulting
  "McKinsey & Company",
  "Boston Consulting Group",
  "Bain & Company",
  "EY-Parthenon",
  "Strategy& (PwC)",
  "Oliver Wyman",
  "Deloitte S&A (Monitor)",
  "Accenture",
  // Asset Management / IM
  "Goldman Sachs Asset Management",
  "Morgan Stanley Investment Mgmt",
  "J.P. Morgan Asset Management",
  "Citi Investment Strategies",
  "Bank of America",
  "UBS Asset Management",
  "Barclays Investment Solutions",
  "Deutsche Bank",
  "BNP Paribas Asset Mgmt",
  "Credit Suisse AM",
  // Private Equity / Alternatives
  "Blackstone",
  "KKR",
  "Apollo Global Management",
  "Carlyle Group",
  "Brookfield Asset Management",
  "TPG",
  "Bain Capital",
  "Vista Equity Partners",
  "General Atlantic",
  "Silver Lake Partners",
  "Hellman & Friedman",
  "Oaktree Capital",
  "Ares Management",
  "StepStone Group",
  "Partners Group",
  // Hedge Funds / Quant
  "Bridgewater Associates",
  "Citadel",
  "Jane Street",
  "Two Sigma",
  "DE Shaw",
  "Renaissance Technologies",
  "Point72",
  "Millennium Mgmt",
  "Jump Trading",
  "HRT",
  // Big Tech (Strategy/Data)
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Palantir",
  "Stripe",
  "OpenAI",
  "Nvidia",
  "Tesla",
  "Apple",
  "Adobe",
  "ASML",
  "Broadcom",
  // Venture Capital / Growth Equity
  "Sequoia Capital",
  "Andreessen Horowitz",
  "Insight Partners",
  "General Catalyst",
  "Accel",
  "Lightspeed Venture Partners",
  "Battery Ventures",
  "Bessemer Venture Partners",
  "Redpoint Ventures",
  "Founders Fund",
  "Coatue",
  "Thrive Capital",
  // Add more as needed...
];
